---
blank_issues_enabled: false
contact_links:
  - name: SNIPs Community Support
    url: https://github.com/starknet-community-libs/SNIPs/discussions
    about: Please ask and answer questions here.
